### ISSUE TITLE
[BUG] github按钮打开了错误的连接

### ISSUE THREAD

**Issue by hyplant** [Vera-Firefly/PojavLauncher-Experimental-Edition#2]
### Describe the bug

在主页上点击github按钮，
它会打开https://github.com/Vera-Firefly/PojavLauncher-Beta-Zink
而不是打开https://github.com/Vera-Firefly/PojavLauncher-Experimental-Edition

### The log file and images/videos

无

### Steps To Reproduce

```markdown
1. 打开应用程序
2. 点击github按钮
```

### Expected Behavior

打开https://github.com/Vera-Firefly/PojavLauncher-Experimental-Edition

### Platform

```markdown
无
```

### Anything else?

无

**Comment by Vera-Firefly** [comment]
仔细看这个存储库的简介,Pojav EXP就是基于Pojav Beta·Zink而制作的,并且Beta Zink那里也给了相对应的链接
